version: '3.8'

services:
  db_primary:
    image: mongo:latest
    ports:
      - "27020:27017"
    command: mongod --replSet rs0
    networks:
      - mynetwork
    container_name: mongodb_master

  db_secondary1:
    image: mongo:latest
    container_name: mongodb_slave1
    depends_on:
      - db_primary
    command: mongod --replSet rs0
    networks:
      - mynetwork

  db_secondary2:
    image: mongo:latest
    container_name: mongodb_slave2
    depends_on:
      - db_primary
    command: mongod --replSet rs0
    networks:
      - mynetwork

  db_secondary3:
    image: mongo:latest
    container_name: mongodb_slave3
    depends_on:
      - db_primary
    command: mongod --replSet rs0
    networks:
      - mynetwork

  db_secondary4:
    image: mongo:latest
    container_name: mongodb_slave4
    depends_on:
      - db_primary
    command: mongod --replSet rs0
    networks:
      - mynetwork


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    container_name: pad_redis

  delivery_api:
    build: .
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    container_name: delivery_pad
    environment:
      MONGO_DB: mydatabase
      MONGO_USER: myuser
      MONGO_PASSWORD: mypassword
      MONGO_HOST: db
      MONGO_PORT: 27017
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: driversdb
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
